server:
  port: 9000
spring:
  application:
    name: spring-zuul-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    invoker:
      path: /member/**
      serviceId: zhushan-member